services:
  redis:
    volumes:
      - redis-data:/data

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - MongoConnection__ConnectionString=mongodb://localhost:27017
      - MongoConnection__Database=AS
      - MongoConnection__RabbitMessagesCollectionName=RabbitMessages
      - MongoConnection__MetricsCollectionName=Metrics
      - ConnectionStrings__ASGenericDb=Server=localhost;Port=5433;Database=ASGenericDb;User Id=postgres;Password=1111;
      - ConnectionStrings__ElasticSearch=http://localhost:9200
      - ConnectionStrings__Redis=localhost:6379
      - Logging__LogLevel__Default=Trace
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
      - Consul__Host=localhost
      - Consul__Port=8500
      - Consul__Discovery__ServiceName=teamtasks-identity-service
      - Consul__Discovery__Hostname=teamtasks-identity-api
      - Consul__Discovery__Port=8080
      - MessageBroker__AmqpLink=amqps://dgpswpjt:tbQvnOh93n-sdqDMjXAjfB53OiShmOka@chimpanzee.rmq.cloudamqp.com/dgpswpjt
      - MessageBroker__QueueName=User
      - Jwt__Secret=secretsecret123456
      - Jwt__ValidIssuers__0=https://localhost:7135
      - Jwt__ValidAudiences__0=https://localhost:7135
      - Jwt__Expire=3600
      - Jwt__RefreshTokenExpire=20160
      - AllowedHosts=*
    ports:
      - 8082
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  elasticsearch:
    container_name: elasticsearch

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana

    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

  prometheus:
    restart: always

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    restart: always
    depends_on:
      - prometheus

    volumes:
      - grafana-storage:/var/lib/grafana